#!/usr/bin/env python3
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
#from urllib2 import urlopen
import numpy as np
import sys

argvs = sys.argv

fname = argvs[1]
output = fname.split(".")[0] + ".png"

nba = pd.read_csv(fname, index_col=0)
plt.figure(figsize=(84, 64))

fig, ax = plt.subplots()
#heatmap = ax.pcolor(nba, cmap=plt.cm.Reds, alpha=0.8)
heatmap = ax.pcolormesh(nba.values, cmap=plt.cm.Reds, alpha=0.8)

fig = plt.gcf()
ax.set_frame_on(False)

# put the major ticks at the middle of each cell
ax.set_yticks(np.arange(nba.shape[0]) + 0.5, minor=True)
ax.set_xticks(np.arange(nba.shape[1]) + 0.5, minor=False)

# want a more natural, table-like display
ax.invert_yaxis()
ax.xaxis.tick_top()

# Set the labels

# label source:https://en.wikipedia.org/wiki/Basketball_statistics
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
      34, 36, 38, 40, 42, 44, 46, 48,
      52, 56, 60, 64,
      100, 104, 108, 112, 116,
      120, 124, 128, 132, 136, 140,
      149, 153, 157, 161, 165]

ax.set_xticklabels(labels, minor=False)
ax.set_yticklabels(nba.index, minor=False)
#ax.yaxis_date()
#ax.yaxis.set_major_locator(mdates.AutoDateLocator())
#ax.yaxis.set_major_formatter(mdates.DateFormatter("%H:%M:%S"))

# rotate
plt.xticks(rotation=90, fontsize=10)
#plt.yticks(fontsize=18)
plt.tick_params(labelsize=10)


ax.grid(False)

# Turn off all the ticks
ax = plt.gca()

for t in ax.xaxis.get_major_ticks():
	t.tick1On = False
	t.tick2On = False
#for t in ax.yaxis.get_major_ticks():
#	t.tick1On = False
#	t.tick2On = False


#plt.show()
#plt.title("Channel Utilization", fontsize=20)
plt.colorbar(heatmap)
plt.xlabel("channel", fontsize=18)
plt.ylabel("time", fontsize=18)
plt.savefig(output)
